const exam2 = {
  id: "exam2",
  name: "Find Output Challenge ",
  date: "2025-04-04",
  totalMarks: 50,
  score: [
    { name: "ANKIT KUMAR THAKUR", roll_no: "24CS20", marks: 44 },
    { name: "Virat Raj", roll_no: "24CS107", marks: 41 },
    { name: "Harshit Kumar Thakur", roll_no: "24CS17", marks: 41 },
    { name: "RITIK KUMAR RAI", roll_no: "24EE20", marks: 39 },
    { name: "Nityanand Tiwari", roll_no: "24CS02", marks: 38 },
    { name: "VIKASH KUMAR YADAV", roll_no: "24CS42", marks: 35 },
    { name: "Ranjeet Kumar", roll_no: "24CS11", marks: 35 },
    { name: "Khushi raj", roll_no: "24CS34", marks: 35 },
    { name: "suman kumar", roll_no: "24cs30", marks: 35 },
    { name: "Pranav Prakash", roll_no: "24CS71", marks: 32 },
    { name: "Nisha Kumari", roll_no: "24CS09", marks: 32 },
    { name: "Suman Baitha", roll_no: "24CS72", marks: 32 },
    { name: "Ritesh Kumar", roll_no: "24cs49", marks: 30 },
    { name: "Nikhil Kumar Sharma", roll_no: "24EC19", marks: 30 },
    { name: "SIBU PATHAK", roll_no: "24CS55", marks: 30 },
    { name: "Divya Kumari", roll_no: "24cs07", marks: 29 },
    { name: "PRINCE RAJ KASHYAP", roll_no: "24CS08", marks: 29 },
    { name: "Anushka Deep", roll_no: "24CS14", marks: 26 },
    { name: "AYUSH ANAND", roll_no: "24CS80", marks: 26 },
    { name: "Anshu Kumari", roll_no: "24cs19", marks: 26 },
    { name: "Madhu Kumari", roll_no: "24CS88", marks: 26 },
    { name: "Arya sinha", roll_no: "24cs64", marks: 24 },
    { name: "Kajal kumari", roll_no: "24cs94", marks: 24 },
    { name: "Shivam Kumar", roll_no: "24CS104", marks: 23 },
    { name: "shalu kumari", roll_no: "24cs01", marks: 23 },
    { name: "Radhika kumari", roll_no: "24cs18", marks: 23 },
    { name: "AKHIL TIWARI", roll_no: "24CS24", marks: 23 },
    { name: "Kunal Kumar", roll_no: "24CS70", marks: 21 },
    { name: "RIYA KUMARI", roll_no: "24CS63", marks: 21 },
    { name: "juhi kumari", roll_no: "24cs62", marks: 20 },
    { name: "BULBUL SINHA", roll_no: "24CS77", marks: 20 },
    { name: "Shubham Raj", roll_no: "24cs104p", marks: 20 },
    { name: "Amisha Kumari", roll_no: "24CS29", marks: 18 },
    { name: "Tamanna", roll_no: "24CS96", marks: 17 },
    { name: "Suman kumar", roll_no: "24CS69", marks: 17 },
    { name: "Prince Kumar", roll_no: "24CS111P", marks: 17 },
    { name: "Arun Kumar", roll_no: "24CS60", marks: 15 },
    { name: "Manav Raj Kashyap", roll_no: "24cs56", marks: 15 },
    { name: "prince sinha", roll_no: "24CS97", marks: 14 },
    { name: "Ruchi Kumari", roll_no: "24cs103", marks: 14 },
    { name: "Pushpanjali kumari", roll_no: "24cs114", marks: 12 },
    { name: "Aditya Kumar", roll_no: "24CS85", marks: 12 },
    { name: "Anjali Kumari Shukla", roll_no: "24CS92", marks: 11 },
    { name: "Nidhi kumari", roll_no: "24cs106", marks: 8 },
    { name: "Kumari Riya", roll_no: "24CS100", marks: 8 },
    { name: "Priya Kumari", roll_no: "24CS75", marks: 6 },
    { name: "Aditya Tiwari", roll_no: "24CS26", marks: 3 },
    { name: "Archana kumari", roll_no: "24cs48", marks: 3 },
    { name: "Prince Raj", roll_no: "24Cs50p", marks: 3 },
    { name: "Rimjhim kumari", roll_no: "24cs61", marks: 3 },
    { name: "Afsana Praveen", roll_no: "24EC24", marks: 3 },
    { name: "Pravin Prakash", roll_no: "24CS86", marks: 3 },
    { name: "SWEETY KUMARI", roll_no: "24CS112", marks: 3 },
    { name: "Vandana kumari sharma", roll_no: "24EC29", marks: 3 },
    { name: "Shreya srivashtwa", roll_no: "24cs16", marks: 0 },
    { name: "Ankit kumar", roll_no: "24cs91", marks: 0 },
  ],
};

const exam1 = {
  id: "exam1",
  name: "Quiz Quest",
  date: "2025-02-25",
  totalMarks: 50,
  score: [
    { name: "Nikil Kumar Sharma", roll_no: "24EC19", marks: 26 },
    { name: "Nidhi Kumari", roll_no: "24CS106", marks: 28 },
    { name: "Subhankar Sidhu", roll_no: "24CS65", marks: 26 },
    { name: "Suman Baitha", roll_no: "24CS72", marks: 32 },
    { name: "Harshvardhan kumar", roll_no: "24CS74", marks: 14 },
    { name: "Juhi pandey", roll_no: "24CS32p", marks: 20 },
    { name: "Pranav Prakash", roll_no: "24CS71", marks: 36 },
    { name: "Kumari Riya", roll_no: "24CS100", marks: 16 },
    { name: "Tamanna", roll_no: "24CS96", marks: 20 },
    { name: "Nisha kumari", roll_no: "24CS09", marks: 36 },
    { name: "Aanya", roll_no: "24CS115", marks: 20 },
    { name: "Arushi Thakur", roll_no: "24CS82", marks: 18 },
    { name: "vandana kumari sharma ", roll_no: "24EC29", marks: 18 },
    { name: "Archana kumari", roll_no: "24CS48", marks: 14 },
    { name: "Aditya Tiwari", roll_no: "24CS26", marks: 22 },
    { name: "Riya kumari", roll_no: "24CS63p", marks: 18 },
    { name: "Afsana Praveen", roll_no: "24EC24", marks: 16 },
    { name: "Aman Raj", roll_no: "24EC28", marks: 20 },
    { name: "VIKASH KUMAR YADAV", roll_no: "24CS42", marks: 26 },
    { name: "Nityanand Tiwari", roll_no: "24CS02", marks: 32 },
    { name: "Usha kumari", roll_no: "24CS119", marks: 22 },
    { name: "Riya Kumari", roll_no: "24CS38p", marks: 18 },
    { name: "Saloni kumari", roll_no: "24CS95", marks: 26 },
    { name: "Priya Kumari", roll_no: "24CS75", marks: 16 },
    { name: "Puneet Kumar", roll_no: "24CS36", marks: 26 },
    { name: "NISHANT KUMAR VERMA", roll_no: "24CS28", marks: 18 },
    { name: "Mamnit kumar", roll_no: "76", marks: 12 },
    { name: "Rimjhim kumari", roll_no: "24CS61", marks: 18 },
    { name: "Amrit Raj", roll_no: "24EC25", marks: 24 },
    { name: "Nikhil kumar", roll_no: "24CS44", marks: 32 },
    { name: "AKHIL TIWARI", roll_no: "24CS24", marks: 28 },
    { name: "Virat Raj", roll_no: "24CS107", marks: 40 },
    { name: "SUMAN KUMAR", roll_no: "24CS69", marks: 28 },
    { name: "GOLU KUMAR", roll_no: "24CS06", marks: 18 },
    { name: "Rashid ahmad", roll_no: "24CS12", marks: 24 },
    { name: "Juhi Kumari", roll_no: "24CS62", marks: 26 },
    { name: "Anushka deep", roll_no: "24CS14", marks: 22 },
    { name: "Ranjeet Kumar", roll_no: "24CS11", marks: 22 },
    { name: "Rahul Kumar", roll_no: "24CS51", marks: 20 },
    { name: "Harshit Kumar Thakur", roll_no: "24CS17", marks: 36 },
    { name: "Ankit Kumar Thakur", roll_no: "24CS20", marks: 38 },
    { name: "Anjali Kumari Shukla", roll_no: "24CS92", marks: 14 },
    { name: "Pushpanjali kumari", roll_no: "24CS114", marks: 30 },
    { name: "SIBU PATHAK", roll_no: "24CS55", marks: 34 },
    { name: "Shalu kumari", roll_no: "24CS0g", marks: 20 },
    { name: "Aatm Gaurav", roll_no: "24CS101", marks: 36 },
    { name: "Arun Kumar", roll_no: "24CS60", marks: 32 },
    { name: "Radhika Kumari", roll_no: "24CS18", marks: 32 },
    { name: "Sweety Kumari", roll_no: "24CS112", marks: 22 },
    { name: "BULBUL SINHA", roll_no: "24CS77", marks: 14 },
    { name: "Arya sinha", roll_no: "24CS64", marks: 16 },
    { name: "Divya Kumari", roll_no: "24CS07", marks: 28 },
    { name: "Prince Raj kashyap", roll_no: "24CS08p", marks: 24 },
    { name: "Aditya kumar", roll_no: "24CS85", marks: 22 },
    { name: "Shivam Kumar", roll_no: "24CS104", marks: 34 },
    { name: "Amisha kumari", roll_no: "24CS29", marks: 16 },
    { name: "Sameer Alam", roll_no: "24EC02", marks: 14 },
    { name: "Khushi raj", roll_no: "24CS34", marks: 24 },
    { name: "Shreya Srivashtwa", roll_no: "24CS16", marks: 20 },
    { name: "Madhu Kumari", roll_no: "24CS88", marks: 28 },
    { name: "Anshu Kumari", roll_no: "24CS19", marks: 24 },
    { name: "Kajal kumari", roll_no: "24CS94", marks: 28 },
    { name: "Prem kumar", roll_no: "24EC13", marks: 20 },
    { name: "ANSHU RAJ", roll_no: "24EE38", marks: 20 },
    { name: "Prince Sinha", roll_no: "24CS97", marks: 24 },
    { name: "Ruchi kumari", roll_no: "24CS103", marks: 22 },
    { name: "Suman kumari", roll_no: "24CS30", marks: 30 },
    { name: "Dimpal kumari", roll_no: "24CS110", marks: 20 },
    { name: "Ayush Anand", roll_no: "24CS80", marks: 22 },
  ],
};

export { exam1, exam2 };
